name: PostgreSQL Database Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: your_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          # Wait for PostgreSQL to start
          sleep 10

          # Print PostgreSQL version for debugging
          psql -h localhost -U your_username -d your_database -c "SELECT version();"

          # Run any initialization scripts
          PGPASSWORD=your_password psql -h localhost -U your_username -d your_database -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

      - name: Execute Structure and Declarative Constraints
        run: |
          PGPASSWORD=your_password 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/1_tables.sql 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/2_attributes.sql 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/3_primary.sql 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/4_unique.sql 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/5_foreign.sql 
          psql -h localhost -U your_username -d your_database -a -f src/1_structure/6_pupulate_ok.sql 
