name: PostgreSQL Database Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: your_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          # Wait for PostgreSQL to start
          sleep 10
          
          export PGPASSWORD=your_password 

          # Print PostgreSQL version for debugging
          psql -h localhost -U your_username -d your_database -c "SELECT version();"

          # Run any initialization scripts
          psql -h localhost -U your_username -d your_database -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

          # Run script permissions 
          chmod +x ./src/scripts/execute_sql_files.sh
      
      - name: Execute Structure and Declarative Constraints
        run: |
          export PGPASSWORD=your_password 
          ./src/scripts/execute_sql_files.sh 1_structure localhost 5432 your_username your_database your_password 
         
