name: PostgreSQL Database Workflow

on:
  push:
    branches:
      - main

jobs:
  build-execute:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: your_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        run: |
          # Wait for PostgreSQL to start
          sleep 10
          
          export PGPASSWORD=your_password 

          # Print PostgreSQL version for debugging
          psql -h localhost -U your_username -d your_database -c "SELECT version();"

          # Run any initialization scripts
          psql -h localhost -U your_username -d your_database -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

          # Run script permissions 
          chmod +x ./src/scripts/execute_sql_files.sh
      
      - name: Execute Structure and Declarative Constraints
        run: |
          ./src/scripts/execute_sql_files.sh 1_structure localhost 5432 your_username your_database your_password 

      - name: Execute Declarative Constraints and Triggers
        run: |
          ./src/scripts/execute_sql_files.sh 2_automation localhost 5432 your_username your_database your_password 

      - name: Execute Index and Views
        run: |
          ./src/scripts/execute_sql_files.sh 3_index_views localhost 5432 your_username your_database your_password 

      - name: Execute Componnets
        run: |
          ./src/scripts/execute_sql_files.sh 4_components localhost 5432 your_username your_database your_password 
      
      - name: Execute Security
        run: |
          ./src/scripts/execute_sql_files.sh 5_security localhost 5432 your_username your_database your_password 
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint SQL files
        run: |
          sqlfluff lint
